name: swahiliapp

services:
  swahiliapp:
    container_name: swahiliapp
    build:
      context: .
      dockerfile: dockerfile
      args:
        NEXT_PUBLIC_AUTH_API_URL: ${NEXT_PUBLIC_AUTH_API_URL}
        NEXT_PUBLIC_SWAHILI_API_URL: ${NEXT_PUBLIC_SWAHILI_API_URL}
        NEXT_PUBLIC_CORE_API_URL: ${NEXT_PUBLIC_CORE_API_URL}
        NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
    restart: unless-stopped
    ports:
      - "8083:8083"
    environment:
      NODE_ENV: production
      PORT: 8083
      HOSTNAME: 0.0.0.0
      NEXT_PUBLIC_AUTH_API_URL: ${NEXT_PUBLIC_AUTH_API_URL}
      NEXT_PUBLIC_SWAHILI_API_URL: ${NEXT_PUBLIC_SWAHILI_API_URL}
      NEXT_PUBLIC_CORE_API_URL: ${NEXT_PUBLIC_CORE_API_URL}
      NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
    networks:
      - swahili-network

networks:
  swahili-network:
    external: true
    name: swahili-network
